### ISSUE TITLE
单口ram

### ISSUE THREAD

**Issue by PorterLu** [kaitoukito/YSYX-NJU-Group#1]
一生一芯不是支持单口ram吗，这个仓库的ram为什么可以是不止一个口

**Comment by kaitoukito** [comment]
您好，这个项目我后期没有跟进，是由学弟 @WYF19970429 单独完成的。这边是向他咨询的一些结果，供您参考。
![image](https://user-images.githubusercontent.com/34410167/184531366-379a20a9-fa49-45e5-84be-ad2c34d1f609.png)

**Comment by PorterLu** [comment]
好的，十分感谢
